---
# tasks file for ansible-role-cloudforms-refresh-providers

- name: "Getting CloudForms Providers"
  uri:
    url: "https://{{ rhcf_host }}/api/providers"
    method: GET
    validate_certs: False
    headers:
      X-Auth-Token: "{{ rhcf_auth_token }}"
      Content-Type: "application/json"
    status_code: 200
  register: providers

- name: "Setting CloudForms Providers"
  set_fact:
    providers: "{{ providers | json_query('json.resources[*].href') }}"

- name: "Task Result: Setting CloudForms Providers"
  debug: var=providers
